const nodemailer = require('nodemailer');

// Gmail SMTP configuration with YOUR credentials
const emailSender = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'krishansavindu923@gmail.com',        // ✅ ඔබේ Gmail
    pass: 'tzanjlldqfrycjia'                    // ✅ ඔබේ App Password (spaces removed)
  },
  tls: {
    rejectUnauthorized: false
  }
});

// Send alert email function
const sendAlert = async (alertType, message) => {
  const mailOptions = {
    from: 'krishansavindu923@gmail.com',
    to: 'krishansavindu923@gmail.com',           // ඔබේ phone email
    subject: `🚨 Tea Factory Alert: ${alertType}`,
    priority: 'high',
    headers: {
      'X-Priority': '1',
      'X-MSMail-Priority': 'High',
      'Importance': 'high'
    },
    html: `
      <div style="font-family: Arial, sans-serif; background: #f8f9fa; padding: 20px;">
        <div style="background: white; padding: 30px; border-radius: 10px; border-left: 5px solid #dc3545;">
          <h2 style="color: #dc3545; margin-top: 0;">🚨 Tea Factory Security Alert</h2>
          
          <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 10px; border-radius: 5px; margin: 10px 0;">
            <strong>⚠️ IMMEDIATE ACTION REQUIRED</strong>
          </div>
          
          <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 15px 0;">
            <p><strong>🔥 Alert Type:</strong> ${alertType}</p>
            <p><strong>📝 Message:</strong> ${message}</p>
            <p><strong>🕐 Time:</strong> ${new Date().toLocaleString('en-US', { 
              timeZone: 'Asia/Colombo',
              year: 'numeric',
              month: '2-digit', 
              day: '2-digit',
              hour: '2-digit',
              minute: '2-digit',
              second: '2-digit'
            })}</p>
            <p><strong>📍 Location:</strong> Craig Tea Factory, Sri Lanka</p>
            <p><strong>🏭 Factory Status:</strong> Alert Triggered</p>
          </div>
          
          <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 10px; border-radius: 5px; margin: 10px 0;">
            <strong>📱 Check your phone immediately!</strong><br>
            This alert requires immediate attention from security personnel.
          </div>
          
          <hr>
          <p style="color: #666; font-size: 12px;">
            This is an automated security alert from Tea Factory Management System<br>
            Generated by: Tea Factory Security Automation System<br>
            System Time: ${new Date().toISOString()}
          </p>
        </div>
      </div>
    `
  };

  try {
    console.log(`📧 Sending ${alertType} alert email...`);
    
    const info = await emailSender.sendMail(mailOptions);
    
    console.log('✅ Alert email sent successfully!');
    console.log(`📬 Message ID: ${info.messageId}`);
    console.log(`📧 Recipient: krishansavindu923@gmail.com`);
    console.log(`🕐 Sent at: ${new Date().toLocaleString()}`);
    
    return {
      success: true,
      messageId: info.messageId,
      timestamp: new Date().toISOString()
    };
    
  } catch (error) {
    console.error('❌ Failed to send alert email:');
    console.error('Error details:', error.message);
    
    return {
      success: false,
      error: error.message,
      timestamp: new Date().toISOString()
    };
  }
};

module.exports = { sendAlert };
